-- 1. COMANDO CREATE - DDL --
CREATE DATABASE NOMEDOBANCO;

CREATE TABLE NOMEDATABELA(

NOMEDOCAMPO TIPO REGRA,
NOMEDOCAMPO TIPO REGRA,
NOMEDOCAMPO TIPO REGRA,
RESTRIÇÕES -- PRIMARY KEY, FOREING KEY ---
);

-- 2. COMANDO ALTER DDL --

	--INCLUSÃO--
	ALTER TABLE NOMEDATABELA ADD COLUNA TIPO RESTRIÇÃO;
	--EXCLUSÃO (Para fazer exclusão de um campo não pode ter dados inseridos)--
	ALTER TABLE NOMEDATABELA DROP COLUMN COLUNA;

-- 3. COMANDO DROP DDL --
DROP DATABASE NOMEDOBANCO
DROP TABLE NOMEDATABELA
----------------------------------------------------------------------------------------
-- 1. COMANDO INSERT - DML --

INSERT INTO NOMETABELA(COLUNAS,NULL) VALUES (VALORES);
INSERT INTO NOMETABELA VALUES (VALORES);

-- 2. COMANDO INSERT - DML --
UPDATE NOMETABELA SET COLUNA = NOVOVALOR WHERE CONDIÇÃO;

-- 3. COMANDO DELETE - DML --
DELETE FROM NOMEDATABELA WHERE CONDIÇÃO