CREATE DATABASE ESCOLA;
GO
USE ESCOLA;
GO
CREATE TABLE ALUNO(
RA VARCHAR(12) NOT NULL UNIQUE,
NOME VARCHAR(40) NOT NULL,
CIDADE NVARCHAR (30) NOT NULL,
ESTADO CHAR (2) NOT NULL,
SEXO CHAR(1) NOT NULL,
CPF VARCHAR(11) NOT NULL UNIQUE
);
GO

SELECT * FROM ALUNO

INSERT INTO ALUNO (RA,NOME,CIDADE,ESTADO,SEXO,CPF) VALUES
('123456', 'MARIA','VOTORANTIM','SP','F','12345678910'),
('654321','JOSE','RIO DE JANEIRO','RJ','M','555555555'),
('888888','PAULA','RIO DE JANEIRO','RJ','F','222222222');

INSERT INTO ALUNO (NOME,RA,CIDADE,ESTADO,SEXO,CPF) VALUES
('CAIO','1111','VOTORANTIM','SP','M','77777777777');
-- PRESTE ATENÇÃO!!!! USE SEMPRE COM WHERE--

-- UPDATE = ATUALIZAR (VALOR EXISTENTE)--
UPDATE ALUNO SET CIDADE = 'SOROCABA' WHERE RA = '123456';

-- ALTER = ALTERAR-
ALTER TABLE ALUNO ADD BAIRRO VARCHAR(50);

-- SO E POSSIVEL EXCLUIR COLUNAS NULAS (VAZIAS)
ALTER TABLE ALUNO DROP COLUMN BAIRRO

-- DELETE (EXCLUI REGISTROS)
DELETE FROM ALUNO WHERE NOME = 'CAIO' --(NÃO E CORRETO)
DELETE FROM ALUNO WHERE RA = '123456'
DELETE FROM ALUNO  -- cuidado!!!!!! ao usar delete sem where
-- DROP
DROP TABLE ALUNO
DROP DATABASE ESCOLA